ASSOCIATION RULES
The Objective of this assignment is to introduce students to rule mining techniques, particularly focusing on market basket analysis and provide hands on experience.
Dataset:
Use the Online retail dataset to apply the association rules.
Data Preprocessing:
Pre-process the dataset to ensure it is suitable for Association rules, this may include handling missing values, removing duplicates, and converting the data to appropriate format.  
Association Rule Mining:
•	Implement an Apriori algorithm using tool like python with libraries such as Pandas and Mlxtend etc.
•	 Apply association rule mining techniques to the pre-processed dataset to discover interesting relationships between products purchased together.
•	Set appropriate threshold for support, confidence and lift to extract meaning full rules.
Analysis and Interpretation:
•	Analyse the generated rules to identify interesting patterns and relationships between the products.
•	Interpret the results and provide insights into customer purchasing behaviour based on the discovered rules.
Interview Questions:
1.	What is lift and why is it important in Association rules?
2.	What is support and Confidence. How do you calculate them?
3.	What are some limitations or challenges of Association rules mining?

In [1]:
import numpy as np
import pandas as pd
from mlxtend.frequent_patterns import association_rules,apriori
#from mlxtend.preprocessing import TransactionEncoder
# conda install -c conda-forge mlxtend

In [2]:
#data is sepereted by coma in the excel from text to columns
df=pd.read_excel("Copy of Online retail.xlsx",header=None)
df.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,whole wheat pasta,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,soup,light cream,shallot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,frozen vegetables,spaghetti,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(7501, 20)

Apriori Algorithhm

Data Preprocessing:
Pre-process the dataset to ensure it is suitable for Association rules, this may include handling missing values, removing duplicates, and converting the data to appropriate format.

In [10]:
#converting the categorical into seperate columns which machine can understand
#we are encoding the data
data=pd.get_dummies(df,dtype='int')
data

,0_almonds,0_antioxydant juice,0_asparagus,0_avocado,0_babies food,0_bacon,0_barbecue sauce,0_black tea,0_blueberries,0_body spray,...,16_antioxydant juice,16_french fries,16_frozen smoothie,17_frozen smoothie,17_protein bar,17_spinach,18_cereals,18_mayonnaise,18_spinach,19_olive oil
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,1,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
#if the duplicates are deleted we are losing the data.
data.duplicated().sum()

2325

In [14]:
frequent_items=apriori(data,min_support=0.01,use_colnames=True)
frequent_items

C:\Users\moham\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support                         itemsets
0   0.076790                      (0_burgers)
1   0.013065                         (0_cake)
2   0.052126                    (0_chocolate)
3   0.035995                      (0_cookies)
4   0.037195                         (0_eggs)
..       ...                              ...
84  0.010265  (1_frozen vegetables, 0_shrimp)
85  0.013332   (1_mineral water, 0_spaghetti)
86  0.011865     (1_ground beef, 2_spaghetti)
87  0.017731   (1_spaghetti, 2_mineral water)
88  0.012798   (3_mineral water, 2_spaghetti)

[89 rows x 2 columns]

In [30]:
rules=association_rules(frequent_items,metric='lift',min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(1_frozen vegetables),(0_shrimp),0.031196,0.043328,0.010265,0.329060,7.594701,1.0,0.008914,1.425868,0.896290,0.159751,0.298673,0.282991
1,(0_shrimp),(1_frozen vegetables),0.043328,0.031196,0.010265,0.236923,7.594701,1.0,0.008914,1.269602,0.907656,0.159751,0.212352,0.282991
2,(1_mineral water),(0_spaghetti),0.064525,0.047194,0.013332,0.206612,4.377947,1.0,0.010286,1.200933,0.824803,0.135501,0.167314,0.244549
3,(0_spaghetti),(1_mineral water),0.047194,0.064525,0.013332,0.282486,4.377947,1.0,0.010286,1.303773,0.809800,0.135501,0.232995,0.244549
4,(1_ground beef),(2_spaghetti),0.038795,0.037195,0.011865,0.305842,8.222653,1.0,0.010422,1.387011,0.913837,0.185031,0.279025,0.312419
5,(2_spaghetti),(1_ground beef),0.037195,0.038795,0.011865,0.318996,8.222653,1.0,0.010422,1.411454,0.912318,0.185031,0.291511,0.312419
6,(1_spaghetti),(2_mineral water),0.054793,0.049993,0.017731,0.323601,6.472882,1.0,0.014992,1.404506,0.894523,0.203675,0.288006,0.339134
7,(2_mineral water),(1_spaghetti),0.049993,0.054793,0.017731,0.354667,6.472882,1.0,0.014992,1.464681,0.890004,0.203675,0.317257,0.339134
8,(3_mineral water),(2_spaghetti),0.026796,0.037195,0.012798,0.477612,12.840743,1.0,0.011802,1.843084,0.947513,0.250000,0.457431,0.410849
9,(2_spaghetti),(3_mineral water),0.037195,0.026796,0.012798,0.344086,12.840743,1.0,0.011802,1.483737,0.957746,0.250000,0.326026,0.410849

In [1]:
#As we can see that the best association rule is with index 8 i.e.,mineral water and spaghetti as consequent

1)What is lift and why is it important in Association rules?
Lift is a metric used in association rule mining to measure the strength of a relationship between two items compared to their expected occurrence if they were independent.
->the rule with high lift is condidered to be the best rule of all
->In market basket analysis, a lift value greater than 1 suggests that customers who buy product A are more likely to buy product B than expected. This helps businesses design promotions, optimize product placements, and improve recommendations.
2)What is support and Confidence. How do you calculate them?
Support:Support measures how frequently an item or itemset appears in the dataset.
Confidence:Confidence measures how often a rule is found to be true in transactions containing the antecedent.
3)What are some limitations or challenges of Association rules mining?
->Association rule mining is a powerful technique for discovering relationships between items
->High Computational Complexity
->Difficulty in Setting Threshold
->Generation of Too Many Rules
->Lack of Causal Relationships