Recommendation System

Data Description:

Unique ID of each anime.
Anime title.
Anime broadcast type, such as TV, OVA, etc.
anime genre.
The number of episodes of each anime.
The average rating for each anime compared to the number of users who gave ratings.


Number of community members for each anime.
Objective:
The objective of this assignment is to implement a recommendation system using cosine similarity on an anime dataset. 
Dataset:
Use the Anime Dataset which contains information about various anime, including their titles, genres,No.of episodes and user ratings etc.

Tasks:

Data Preprocessing:

Load the dataset into a suitable data structure (e.g., pandas DataFrame).
Handle missing values, if any.
Explore the dataset to understand its structure and attributes.

Feature Extraction:

Decide on the features that will be used for computing similarity (e.g., genres, user ratings).
Convert categorical features into numerical representations if necessary.
Normalize numerical features if required.

Recommendation System:

Design a function to recommend anime based on cosine similarity.
Given a target anime, recommend a list of similar anime based on cosine similarity scores.
Experiment with different threshold values for similarity scores to adjust the recommendation list size.

Evaluation:

Split the dataset into training and testing sets.
Evaluate the recommendation system using appropriate metrics such as precision, recall, and F1-score.
Analyze the performance of the recommendation system and identify areas of improvement.

Interview Questions:
1. Can you explain the difference between user-based and item-based collaborative filtering?
2. What is collaborative filtering, and how does it work?

In [1]:
import pandas as pd 
import numpy as np
import statistics as st
anime=pd.read_csv("anime.csv")

In [2]:
anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [3]:
anime.shape

(12294, 7)

In [4]:
anime.anime_id.nunique()

12294

In [5]:
anime.name.nunique()

12292

In [6]:
anime.type.nunique()

6

In [7]:
anime.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [8]:
anime.genre.mode()

0    Hentai
Name: genre, dtype: object

In [9]:
# Get the most frequent genre
anime['genre'].fillna(anime['genre'].mode()[0], inplace=True)
anime['type'].fillna(anime['type'].mode()[0],inplace=True)
anime['rating'].fillna(anime['rating'].mean(),inplace=True)

C:\Users\moham\AppData\Local\Temp\ipykernel_2040\1799519710.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  anime['genre'].fillna(anime['genre'].mode()[0], inplace=True)
C:\Users\moham\AppData\Local\Temp\ipykernel_2040\1799519710.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  anime['type'].fillna(anime['type'].mode()[0],inplace=True)
C:\Users\moham\AppData\Local\Temp\ipykernel_2040\1799519710.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  anime['rating'].fillna(anime['rating'].mean(),inplace=True)

In [10]:
anime.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [11]:
anime['genre']=anime['genre'].str.split(',')
anime=anime.explode('genre')

In [12]:
anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,Drama,Movie,1,9.37,200630
0,32281,Kimi no Na wa.,Romance,Movie,1,9.37,200630
0,32281,Kimi no Na wa.,School,Movie,1,9.37,200630
0,32281,Kimi no Na wa.,Supernatural,Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,Action,TV,64,9.26,793665
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [13]:
name_df=anime.pivot_table(index="anime_id",
                          columns="name", 
                          values="rating")#resetindex(drop=True)

name_df

name,&quot;0&quot;,"&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu",&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi,&quot;Bungaku Shoujo&quot; Memoire,&quot;Bungaku Shoujo&quot; Movie,&quot;Eiji&quot;,&quot;Eiyuu&quot; Kaitai,.hack//G.U. Returner,.hack//G.U. Trilogy,.hack//G.U. Trilogy: Parody Mode,...,s.CRY.ed,vivi,xxxHOLiC,xxxHOLiC Kei,xxxHOLiC Movie: Manatsu no Yoru no Yume,xxxHOLiC Rou,xxxHOLiC Shunmuki,Üks Uks,ēlDLIVE,◯
anime_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
name_df.index=anime.anime_id.unique()

In [15]:
name_df.fillna(0,inplace=True)
name_df

name,&quot;0&quot;,"&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu",&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi,&quot;Bungaku Shoujo&quot; Memoire,&quot;Bungaku Shoujo&quot; Movie,&quot;Eiji&quot;,&quot;Eiyuu&quot; Kaitai,.hack//G.U. Returner,.hack//G.U. Trilogy,.hack//G.U. Trilogy: Parody Mode,...,s.CRY.ed,vivi,xxxHOLiC,xxxHOLiC Kei,xxxHOLiC Movie: Manatsu no Yoru no Yume,xxxHOLiC Rou,xxxHOLiC Shunmuki,Üks Uks,ēlDLIVE,◯
32281,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5114,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9253,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9969,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9316,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5543,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5621,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6133,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26081,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances
#from scipy.spatial.distance import cosine, correlation

In [17]:
anime_sim=1-pairwise_distances(name_df.values,metric='cosine')

In [18]:
anime_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [19]:
anime_sim_df=pd.DataFrame(anime_sim)
anime_sim_df

,0,1,2,3,4,5,6,7,8,9,...,12284,12285,12286,12287,12288,12289,12290,12291,12292,12293
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12289,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
12290,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
12291,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
12292,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
12293,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [20]:
#Set the index and column names to anime ids
anime_sim_df.index=anime.anime_id.unique()
anime_sim_df.columns=anime.anime_id.unique()

In [21]:
anime_sim_df.iloc[0:10,0:10]

       32281  5114   28977  9253   9969   32935  11061  820    15335  15417
32281    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5114     0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
28977    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
9253     0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0
9969     0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0
32935    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0
11061    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0
820      0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0
15335    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0    0.0
15417    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0

In [22]:
np.fill_diagonal(anime_sim,0)
anime_sim_df.iloc[0:10,0:10]

       32281  5114   28977  9253   9969   32935  11061  820    15335  15417
32281    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
5114     0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
28977    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
9253     0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
9969     0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
32935    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
11061    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
820      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
15335    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
15417    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0

In [23]:
anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,Drama,Movie,1,9.37,200630
0,32281,Kimi no Na wa.,Romance,Movie,1,9.37,200630
0,32281,Kimi no Na wa.,School,Movie,1,9.37,200630
0,32281,Kimi no Na wa.,Supernatural,Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,Action,TV,64,9.26,793665
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [24]:
name_df

name,&quot;0&quot;,"&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu",&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi,&quot;Bungaku Shoujo&quot; Memoire,&quot;Bungaku Shoujo&quot; Movie,&quot;Eiji&quot;,&quot;Eiyuu&quot; Kaitai,.hack//G.U. Returner,.hack//G.U. Trilogy,.hack//G.U. Trilogy: Parody Mode,...,s.CRY.ed,vivi,xxxHOLiC,xxxHOLiC Kei,xxxHOLiC Movie: Manatsu no Yoru no Yume,xxxHOLiC Rou,xxxHOLiC Shunmuki,Üks Uks,ēlDLIVE,◯
32281,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5114,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28977,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9253,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9969,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9316,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5543,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5621,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6133,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26081,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
anime_sim_df.idxmax(axis=1).head(10)

32281    32281
5114     32281
28977    32281
9253     32281
9969     32281
32935    32281
11061    32281
820      32281
15335    32281
15417    32281
dtype: int64

In [26]:
anime[(anime['anime_id']==32281)|(anime['anime_id']==5114)]

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,Drama,Movie,1,9.37,200630
0,32281,Kimi no Na wa.,Romance,Movie,1,9.37,200630
0,32281,Kimi no Na wa.,School,Movie,1,9.37,200630
0,32281,Kimi no Na wa.,Supernatural,Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,Action,TV,64,9.26,793665
1,5114,Fullmetal Alchemist: Brotherhood,Adventure,TV,64,9.26,793665
1,5114,Fullmetal Alchemist: Brotherhood,Drama,TV,64,9.26,793665
1,5114,Fullmetal Alchemist: Brotherhood,Fantasy,TV,64,9.26,793665
1,5114,Fullmetal Alchemist: Brotherhood,Magic,TV,64,9.26,793665
1,5114,Fullmetal Alchemist: Brotherhood,Military,TV,64,9.26,793665
1,5114,Fullmetal Alchemist: Brotherhood,Shounen,TV,64,9.26,793665

In [27]:
def recommend_animes(anime_id,anime_sim_df,anime,num_recommendations=5):
    # Find the most similar user to the target user
    similar_users = anime_sim_df.loc[anime_id].sort_values(ascending=False).index[0:]  # Exclude the user itself
        # animes rated by the target user
    animes_watched_by_user = anime[anime['anime_id'] == anime_id]['name'].tolist()
    recommendations=[]
    for similar_user in similar_users:
        animes_watched_by_similar_user= anime[anime['anime_id'] == (similar_user)]['name'].tolist()
        for name in animes_watched_by_similar_user:
            if name not in animes_watched_by_user and name not in recommendations:
                recommendations.append(name)
                if len(recommendations) == num_recommendations:
                    return recommendations
    return recommendations

In [28]:
anime_id_to_recommend=int(input("enter anime id"))
recommendations=recommend_animes(anime_id_to_recommend,anime_sim_df,anime,5)
print(f"Recommended animes for user {anime_id_to_recommend}: {recommendations}")

enter anime id 5114

Recommended animes for user 5114: ['Kimi no Na wa.', 'Taku Boda', 'Backkom Mission Impossible', 'Backkom Specials', 'Backstage Idol Story']

## Evaluation:
Split the dataset into training and testing sets.

Evaluate the recommendation system using appropriate metrics such as precision, recall, and F1-score.

Analyze the performance of the recommendation system and identify areas of improvement.

In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv("anime.csv")
# Splitting data (80% training, 20% testing)
train, test = train_test_split(df, test_size=0.2, random_state=42)

In [35]:
#calculating the metrics

from sklearn.metrics import precision_score, recall_score, f1_score

# Function to calculate Precision, Recall & F1-score
def evaluate_recommendation(y_true, y_pred, k=10):
    precision = precision_score(y_true, y_pred, average="micro")
    recall = recall_score(y_true, y_pred, average="micro")
    f1 = f1_score(y_true, y_pred, average="micro")

    return {"Precision": precision, "Recall": recall, "F1-score": f1}

In [39]:
def get_predictions(test, df, anime_sim):
    predictions = []
    # df = df.reset_index(drop=True)  # No need to reset index here

    for anime_id in test["anime_id"]:
        if anime_id not in anime_sim.index:  # Check if anime_id is in the index of the similarity matrix
            print(f"Warning: Anime ID {anime_id} not found in similarity matrix!")
            continue  # Skip the missing anime ID

        # Access the similarity scores using the anime_id directly from the similarity matrix
        # anime_sim here is user_movie which has anime_id as index and anime_id as columns
        sim_scores = list(enumerate(anime_sim.loc[anime_id])) # Access the row by index (anime_id)
        sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:6]  # Top 5 recommendations (excluding self)

        # Get the anime_ids of the recommended anime from the columns of the similarity matrix
        recommended_ids = [anime_sim.columns[i[0]] for i in sim_scores]
        predictions.append(recommended_ids)

    return predictions
# Convert actual values (watched anime) to binary (1 if watched, 0 otherwise)
# Ensure y_true covers all anime_ids present in df
all_anime_ids_in_df = df["anime_id"].unique().tolist()
y_true = [1 if anime_id in test["anime_id"].values else 0 for anime_id in all_anime_ids_in_df]

# Flatten the list of lists
predicted_anime = [item for sublist in get_predictions(test, df, name_df) for item in sublist]

# Convert predicted recommendations to binary
y_pred = [1 if anime_id in predicted_anime else 0 for anime_id in all_anime_ids_in_df]

# Evaluate performance
scores = evaluate_recommendation(y_true, y_pred)
print(scores)

{'Precision': 0.7999837319017407, 'Recall': 0.7999837319017407, 'F1-score': 0.7999837319017407}

In [45]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd # Ensure pandas is imported if not already

cos_sim = cosine_similarity(name_df, name_df)

# Define the index and columns for the similarity matrix using the index of user_movie
similarity_index = name_df.index

# convert to a DataFrame for easy lookup
sim_df = pd.DataFrame(cos_sim, index=similarity_index, columns=similarity_index)

# Define anime_titles using the unique anime names from the original dataframe (This is fine for the recommend function)
anime_titles = df['name'].unique()


def recommend(anime_name, threshold=0.5):
    """
    Return all anime whose cosine-similarity to `anime_name` is >= threshold,
    sorted descending by similarity.
    """
    # Need to find the anime_id for the given anime_name
    anime_id_to_recommend = df[df['name'] == anime_name]['anime_id'].iloc[0]

    # get the row of similarity scores using the anime_id
    scores = sim_df.loc[anime_id_to_recommend]

    # drop self (similarity to the same anime_id)
    scores = scores.drop(anime_id_to_recommend)
    # filter by threshold
    filtered_scores = scores[scores >= threshold]

    # Get the anime_ids of the recommended anime
    recommended_anime_ids = filtered_scores.index.tolist()

    # Get the names of the recommended anime
    recommended_anime_names = df[df['anime_id'].isin(recommended_anime_ids)]['name'].tolist()


    score_dict = filtered_scores.to_dict()
    recommended_anime_names.sort(key=lambda name: score_dict[df[df['name'] == name]['anime_id'].iloc[0]], reverse=True)


    return recommended_anime_names


# choose the thresholds you want to try
thresholds = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

# for a given test anime, see how list‐size changes
test_title = "Naruto"    # or any title in your set
results = []
for t in thresholds:
    recs = recommend(test_title, threshold=t)
    results.append((t, len(recs)))

# print the threshold vs. number of recs
for t, count in results:
    print(f"threshold≥{t:.1f}: {count} recommendations")

threshold≥0.1: 0 recommendations
threshold≥0.2: 0 recommendations
threshold≥0.3: 0 recommendations
threshold≥0.4: 0 recommendations
threshold≥0.5: 0 recommendations
threshold≥0.6: 0 recommendations
threshold≥0.7: 0 recommendations
threshold≥0.8: 0 recommendations
threshold≥0.9: 0 recommendations

## Interview Questions:
1.Can you explain the difference between user-based and item-based collaborative filtering?
What is collaborative filtering, and how does it work?